config/routes.rb
Rails.application.routes.draw do
    root "dm#index"


    

    
    resources :players
    resources :characters
    resources :dms
    resources :campaigns
    resources :weapons

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
end

app/models/character.rb
class Character < ApplicationRecord
    validates :name, presence: true
    validates :owner, presence: true

    # belongs_to :player
end

app/models/dm.rb
class Dm < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
    
    has_many :characters
end

app/models/weapon.rb
class Weapon < ApplicationRecord
    validates :name, presence: true
    validates :weapon_types, presence: true
    validates :range, presence: true
    validates :damage, presence: true
   

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
   def index
        @campaigns = Campaign.all
    
   end 

    def show 
        @campaign = Campaign.find(params[:id])
    end 

    def new
        @campaign = Campaign.new
    end

    def create 
        @campaign = Campaign.new(campaign_params)
    
        if @campaign.save
            redirect_to root_path
        else  
            render :new
        end
    end 

    def edit
        @campaign = Campaign.find(params[:id])
    end

    def update
        @campaign = Campaign.find(params[:id])

        if @campaign.update(campaign_params)
            redirect_to root_path
        else 
            render :edit
        end
    end

    def destroy
        @campaign = Campaign.find(params[:id])
        @campaign.destroy
        redirect_to root_path
    end 

    private
    def campaign_params
        params.require(:campaign).permit(:name)
    end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
    # This action uses query string parameters b/c it gets run by an HTTP GET request
    # but this does not make any difference to way in which the parameters are accessed. 
    # require "pry"
    
    def index  
        @characters = Character.all
    end 

    # Show uses POST parameters. they are most likely coming from an HTMl form
    # which the user has submitted. 

    def show 
        @character = Character.find(params[:id])
    end 
    # Uses GET request to gather information to be saved later. Does not save
    def new 
        @character = Character.new
    end 
    
    #This action actually saves the information and checks validations
    def create
        @character = Character.new(character_params)
        # binding.pry
        if @character.save
            redirect_to @character
        else
            render :new
        end
    end

    # similar to new/create, this allows to take saved information and edit the character.
    # update saves the changes.
    def edit
        @character = Character.find(params[:id])
    end

    def update
        @character = Character.find(params[:id])

        if @character.update(character_params)
            redirect_to @characters
        else
            render :edit
        end 
    end 
    
    def destroy
        @characters = Character.find(params[:id])
        @characters.destroy

        redirect_to root_path
    end 

    private
    def character_params
        params.require(:character).permit(:name, :owner, :race, :role, :level)
    end 
end

app/controllers/dm_controller.rb
class DmController < ApplicationController
    def index
        @dms = Dm.all 
        @players = Player.all
        @characters = Character.all
        @campaigns = Campaign.all
        @weapons = Weapon.all
    end 

    def show 
        @dm = Dm.find(params[:id])
    end    

    def new
        @dm = Dm.new
    end

    def create
        @dm = Dm.new(dm_params)

        if @dm.save
            redirect_to @dm
        else
            render :new
        end
    end

    # similar to new/create, this allows to take saved information and edit the dm.
    # update saves the changes.
    def edit
        @dm = Dm.find(params[:id])
    end

    def update
        @dm = Dm.find(params[:id])

        if @dm.update(dm_params)
            redirect_to @dm
        else
            render :edit
        end 
    end 

    private
    def dm_params
        params.require(:name)
    end
end 

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @players = Player.all
        @characters = Character.all
    end 
end 

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    def index
        @players = Player.all 
    end 

    def show 
        @player = Player.find(params[:id])
    end    

    def new 
        @player = Player.new
    end

    def create
        @player = Player.new(player_params)

        if @player.save
            redirect_to @player
        else
            render :new
        end
    end

    # similar to new/create, this allows to take saved information and edit the Player.
    # update saves the changes.
    def edit
        @player = Player.find(params[:id])
    end 

    def update
        @player = Player.find(params[:id])

        if @player.update(player_params)
            redirect_to @player
        else
            render :edit
        end 
    end 

    def destroy
        @player = Player.find(params[:id])
        @player.destroy

        redirect_to root_path
    end

    private
    def player_params
        params.require(:player).permit(:name)
    
    end
end 

# edgegudies_url.

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
    def index 
        @weapons = Weapon.all
    end 

    def show
        @weapon = Weapon.find(params[:id])
    end

    def new 
        @weapon = Weapon.new
    end 
    
    def create 
        
        @weapon = Weapon.new(weapon_params)
        
        if @weapon.save
            redirect_to root_path
        else  
            render :new
        end 
    end 


    def edit 
        @weapon = Weapon.find(params[:id])
    end 

    def update
        @weapon = Weapon.find(weapon_params)

        if weapon.update
            redirect_to @weapons
        else  
            render :edit 
        end 
    end 

    def destroy
        @weapon = Weapon.find(params[:id])
        @wweapon.destroy
        redirect_to :index
    end 

    private 
     def weapon_params
        params.require(:weapon).permit(:name, :weapon_types, :range, :damage) 
     end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/campaigns/_form.html.erb
<%= form_with model: campaign do |form| %>
    <div>
        <%= form.label "Name of Campaign" %><br>
        <%= form.text_field :name %>
        <% campaign.errors.full_messages_for(:name).each do |message| %>
            <%= message %>
        <% end %>
    </div>

    <div>
        <%= form.label :dm_player_id %><br>
        <%= form.text_field :dm_player_id %>
        <% campaign.errors.full_messages_for(:dm_player_id).each do |message| %>
            <%= message %>
        <% end %>
    </div>
    <div>
        <%= form.label "Active Players" %>
        <%= options_for_select([@players]) %> Seems to be broken 
    </div>
    <%= form.submit %>
<% end %>
   

app/views/campaigns/new.html.erb
<h1>New Campaign</h1>

<%= render "form", campaign: @campaign %>

app/views/campaigns/show.html.erb
<h1> Campaign</h1>

<%= render "form", campaign: @campaign %>

app/views/characters/_form.html.erb
<%= form_with model: character do |form| %>
    <div>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
        <% character.errors.full_messages_for(:name).each do |message| %>
            <%= message %>
        <% end %>
    </div>

    <div>
        <%= form.label :owner %><br>
        <%= form.text_field :owner %>
        <% character.errors.full_messages_for(:owner).each do |message| %>
            <%= message %>
        <% end %>
    </div>

    <div>
        
        <%= form.label :race %><br>
        <%= form.text_field :race %>
    </div>

    <div>
        <%= form.label :class %><br>
        <%= form.text_field :role %>
    </div>

    <div>
        <%= form.label :level %><br>
        <%= form.text_field :level %>
    </div>

    <div>
    <%= form.submit %>
    </div>

<% end %>

app/views/characters/edit.html.erb
<h1>Edit Character</h1>

<%= render "form", character: @character %>

app/views/characters/index.html.erb
<h1>Characters</h1>

<ul>
  <% @characters.each do |character| %>
    <li>
       <a href="<%= character_path(character) %>"> 
        <%= character.name %>
        
    </li>
  <% end %>
</ul>

<%= link_to "Home", root_path %>

app/views/characters/new.html.erb
<h1> New Character </h1>

<%= render "form", character: @character %>

app/views/characters/show.html.erb
<h1>Character Sheet</h1>

<ul>
    <li><%=  @character.name %></li>
    <li><%=  @character.owner %></li>
    <li><%=  @character.race %></li>
    <li><%=  @character.class %></li>
    <li><%=  @character.level %></li>
    
</ul>

<%= link_to 'Home', root_path, class: "btn-btn-primary" %>
<%= link_to 'List of characters', characters_path, class: "btn-btn-primary" %>

app/views/dm/index.html.erb
<h1>Game Master Landing Page</h1>

<h2>Player Dashboard</h2>
<table>
  <thead>
    <tr>
      <th>List of players</th>
      <th>Player ID </th>
      <th colspan="3" ></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.id %></td>
        <td><%= link_to "Show", player %></td>
        <td><%= link_to "Edit", edit_player_path(player) %></td>
        <td><%= link_to "Destroy", player, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Player",new_player_path %><br>


<h2>Character Anvil</h2>
<table>
  <thead>
    <tr>
      <th>List of PCs</th>
      <th>Character's Owner </th>
      <th>Character's Race</th>
      <th>Character's level</th>
      <th>Character's Class</th>
      <th colspan="3" ></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.name %></td>
        <td><%= character.owner %></td>
        <td><%= character.race %></td>
        <td><%= character.level %></td>
        <td><%= character.role %></td>
        <td><%= link_to "Show", character %></td>
        <td><%= link_to "Edit", edit_character_path(character) %></td>
        <td><%= link_to "Destroy", character, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Character", new_character_path %><br>  


<h2>Campaign WorkShop</h2>  
<table>
  <thead>
    <th>Name of Campaign</th>
    <th>Campaign's DM</th>
    <th>Current Session</th>
    <th>Player's in Session</th>
    <th colspan="3" ></th>
  </thead>

<tbody>
<% @campaigns.each do |campaign| %> 
  <tr>
  
    <td><%=campaign.name %></td>
    <td><%=campaign.dm_player_id %></td>
    <%# <td><%=campaign.sessions %></td> 
    <td><%# <%= link_to "New Session", new_session_path %>  </td>
    <td><%= link_to "Show", campaign %> </td>
    <td><%= link_to "Edit", edit_campaign_path(campaign) %> </td>
    <td><%= link_to "Destroy", campaign, method: :delete, data: { confirm: "Are you sure?" } %></td> 
    </tr>
    <% end %> 
</table>
 <br> 

<%= link_to "Start a New Campaign", new_campaign_path %><br>  

<h2> HomeBrew Table </h2>
<table>
  <thead>
    <th>Name of Weapon</th>
    <th>Type of Weapon</th>
    <th>Range</th>
    <th>Weapon Damage</th>
    <th>Notes</th>
    <th>Weight</th>
    <th>Cost</th>
    <th>Special</th>
    <th colspan ="3"></th>
  </thead>
  <tbody>
    <% @weapons.each do |weapon| %>
    <tr>
    <td><%= weapon.name%></td>
    <td><%= weapon.weapon_types%></td>
    <td><%= weapon.range%></td>
    <td><%= weapon.damage%></td>
    <td><%= weapon.notes%></td>
    <td><%= weapon.weight%></td>
    <td><%= weapon.cost%></td>
    <td><%= weapon.special%></td>
    <td><%= link_to "Show", weapon %> </td>
    <td><%= link_to "Edit", edit_weapon_path(weapon) %> </td>
    <td><%= link_to "Destroy", weapon, method: :delete, data: { confirm: "Are you sure?" } %></td>
    <% end %>
    </tr>
  </tbody>
    
</table>
  
  
  <%= link_to "Weapons Collection" , weapons_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DndManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with model: player do |form| %>
    <div>
        <%= form.label :name%><br>
        <%= form.text_field :name %>
        <% player.errors.full_messages_for(:name).each do |message| %>
            <%= message %>
        <% end %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/players/edit.html.erb
<h1> Edit player</h1>

<%= render "form", player: @player %>

app/views/players/index.html.erb
<h1> Names of Players </h1>
   
<ul>
  <% @players.each do |player| %>
    <li>
       <a href="<%= player_path(player) %>"> 
        <%= player.name %>
        
    </li>
  <% end %>
</ul>

app/views/players/new.html.erb
<h1> New player</h1>

<%= render "form", player: @player %>

app/views/players/show.html.erb
<h1> Player </h1>
<div>
    <%= @player.name %><br>
</div>




<ul>
    <li><%= link_to "Players", players_path %></li></div>
    <li><%= link_to "Characters", characters_path %></li></div>
    <li><%= link_to "Game Master Dashboard", root_path %></li></div>
</ul>

app/views/weapons/_form.html.erb
<%= form_with model: weapon do |form| %>
    <div>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
        <%# <% weapon.errors.full_messages_for(:name).each do |message| %>
            <%# <%= message %> 
        <%# <% end %> 
    </div>

    <div>
        <%= form.label :weapon_types %><br>
        <%= form.text_field :weapon_types %>
        <%# <% weapon.errors.full_messages_for(:type).each do |message| %> 
            <%# <%= message %> 
        <%# <% end %>
    </div>

    <div>
        <%= form.label :range %><br>
        <%= form.text_field :range %>
        <%# <% weapon.errors.full_messages_for(:range).each do |message| %>
            <%# <%= message %> 
        <%# <% end %> 
    </div>

    <div>
        <%= form.label :hit_dc%><br>
        <%= form.text_field :hit_dc %>
    
    <div>
        <%= form.label :damage%><br>
        <%= form.text_field :damage %>
        <%# <% weapon.errors.full_messages_for(:damage).each do |message| %> 
            <%# <%= message %> 
        <%# <% end %> 
    </div>

    <div>
        <%= form.label :notes%><br>
        <%= form.text_field :notes %>
    </div>

    <div>
        <%= form.label :weight%><br>
        <%= form.text_field :weight %>
    </div>

    <div>
        <%= form.label :cost %><br>
        <%= form.text_field :cost %>
    </div>

    <div>
        <%= form.label :special %><br>
        <%= form.text_field :special %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/weapons/edit.html.erb
<h1> Edit Weapon </h1>

<%= render "form", weapon: @weapons %>

app/views/weapons/index.html.erb
<h1>The collection of Weapons</h1>
    <table>
        <tr>
            <th>Name</th>
            <th>Type of Weapon</th>
            <th>Range</th>
            <th>Hit/Dc</th>
            <th>Damage</th>
            <th>Notes</th>
            <th>Weight</th>
            <th>Cost</th>
            <th>Special Abilities </th>
            <th colspan="3" ></th>
        </tr>
        <tr>
            <% @weapons.each do |weapon| %>
                <td><%= weapon.name %></td>
                <td><%= weapon.weapon_types%></td>
                <td><%= weapon.range%></td>
                <td><%= weapon.hit_dc%></td>
                <td><%= weapon.damage%></td>
                <td><%= weapon.notes%></td> 
                <td><%= weapon.weight%></td>
                <td><%= weapon.cost%></td>
                <td><%= weapon.special%></td>
                <td><%= link_to "Show", weapon %></td>
                <td><%= link_to "Edit", edit_weapon_path(weapon) %></td>
                <td><%= link_to "Destroy", weapon, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
            <% end %>
        </tr>
    </table>
<%= link_to 'Create a Weapon', new_weapon_path %>

app/views/weapons/new.html.erb
<h1> Homebrew Weapon </h1>

<%= render "form", weapon: @weapon %>

app/views/weapons/show.html.erb
<h1>Weapon Details</h1>

<ul>

    [Name of Weapon] = <%=@weapon.name %><br>
    [Weapon Type] = <%= @weapon.weapon_types %><br>
    [Range]<%= @weapon.range %><br>
    [Damage]<%= @weapon.damage %><br>
    [Notes]<%= @weapon.notes %><br>
    [Weight]<%= @weapon.weight %><br>
    [Cost of Purchase ]<%= @weapon.cost %><br>
    [Special]<%=  @weapon.special %><br>

</ul>

<%= link_to 'Home', root_path, class: "btn-btn-primary" %>
<%= link_to 'List of weapons', weapons_path, class: "btn-btn-primary" %>